
Project:
  name: Hyper_test
  # Where to save runs of models
  save_dir: "/results/test"
  # When to save the parameters and update plots
  saveat: 1.0e+4 

Network:
  # Which model to use, based on "networks.py"
  name: "MLP"
  options:
    in_size: 1
    out_size: "dofs" # Can be specified or "dofs" if NNFE
    width_size: 2048
    depth: 8
    activation: "relu"

Optimizer:
  name: "adam"
  learning_rate: 1.0e-3
  epochs: 10
  #epochs: 2.5e+3

  scheduler:
    toggle: True
    boundaries: []
    list:
      s1:
        name: "exponential_decay"
        init_value: 1.0e-5
        decay_rate: 1.0e-2
        transition_steps: 2.5e+3

  options:
    learning_rate:

FE:
  mesh_file: "/home/bthomas/Desktop/Research/JAXFEM_temp/NNFE/mesh_VHL_bigger/mesh.xdmf"
  fiber_file: "/home/bthomas/Desktop/Research/JAXFEM_temp/NNFE/mesh_VHL_bigger/fiber_direction.xdmf"

  constants:
    A1: 12.0
    A2: 8.0
    A3: 26.0
    K: 1.0e+6
    c: 15220.83
    alpha: 2.125
    beta: 1.4

Data:
  PV_file: "/home/bthomas/Desktop/Research/JAXFEM_temp/NNFE/data/VHL-PV-loop-data.txt"
  T_Ca_file: "/home/bthomas/Desktop/Research/JAXFEM_temp/NNFE/data/T_Ca_vals.txt"

Plotting:
  loss:
  











