Project:
  name: single_layer_approx
  # Where to save runs of models - make this more automatic
  save_dir: ${FUN_APPROX_DATA_DIR}/examples/first_examples/single_layer_approx
  # When to save the parameters and update plots
  saveat: 1.0e+2

Network:
  # Which model to use, based on "model.py"
  name: "SingleLayer"
  options:
    batch_size: 16
    in_size: 1
    # f(x) is a scalar-valued function...
    out_size: 1
    layer_width: 128
    activation: "relu"